FROM ubuntu:16.04
MAINTAINER Ray Chang <ray.chang@technexion.com> Po Cheng <po.cheng@technexion.com> Richard Hu <richard.hu@technexion.com>

# Install a basic SSH server
RUN apt-get -q update &&\
    DEBIAN_FRONTEND="noninteractive" apt-get -q upgrade -y -o Dpkg::Options::="--force-confnew" --no-install-recommends &&\
    DEBIAN_FRONTEND="noninteractive" apt-get -q install -y -o Dpkg::Options::="--force-confnew" --no-install-recommends openssh-server &&\
    apt-get -q autoremove &&\
    apt-get -q clean -y && rm -rf /var/lib/apt/lists/* && rm -f /var/cache/apt/*.bin &&\
    sed -i 's|session    required     pam_loginuid.so|session    optional     pam_loginuid.so|g' /etc/pam.d/sshd &&\
    mkdir -p /var/run/sshd

# Install JRE 8
RUN apt-get -q update &&\
    DEBIAN_FRONTEND="noninteractive" apt-get -q install -y -o Dpkg::Options::="--force-confnew" --no-install-recommends default-jre-headless &&\
    apt-get -q autoremove &&\
    apt-get -q clean -y && rm -rf /var/lib/apt/lists/* && rm -f /var/cache/apt/*.bin

# Installing packages
RUN apt-get -q update &&\
    DEBIAN_FRONTEND="noninteractive" apt-get -q install -y -o Dpkg::Options::="--force-confnew" --no-install-recommends \
	gawk wget git git-core diffstat unzip texinfo gcc-multilib build-essential \
	chrpath socat cpio python python3 python3-pip python3-pexpect \
	xz-utils debianutils iputils-ping libsdl1.2-dev xterm \
	language-pack-en coreutils texi2html file docbook-utils \
	python-pysqlite2 help2man desktop-file-utils \
	libgl1-mesa-dev libglu1-mesa-dev mercurial autoconf automake \
	groff curl lzop asciidoc u-boot-tools libreoffice-writer \
	sshpass ssh-askpass zip xz-utils kpartx vim screen sudo &&\
    apt-get -q autoremove &&\
    apt-get -q clean -y && rm -rf /var/lib/apt/lists/* && rm -f /var/cache/apt/*.bin

# Set user jenkins to the image
RUN useradd -m -d /home/jenkins -s /bin/sh jenkins &&\
    echo "jenkins:jenkins" | chpasswd

RUN echo "root:root" | chpasswd
RUN usermod -a -Gsudo jenkins

# Setup repo
RUN mkdir /home/jenkins/bin &&\
    curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > /home/jenkins/bin/repo &&\
    chmod a+x /home/jenkins/bin/repo

ENV LANG en_US.UTF-8
RUN locale-gen $LANG && update-locale

ENV HOME /home/jenkins
ENV PATH /home/jenkins/bin:$PATH
RUN env > /etc/environment

# Standard SSH port
EXPOSE 22

# Default command
CMD ["/usr/sbin/sshd", "-D"]

