SUMMARY = "A QR code generator written purely in Python with SVG, EPS, PNG and terminal output"
DESCRIPTION = "The pyqrcode module is a QR code generator that is simple to use and written in pure python. The module can automates most of the building process for creating QR codes."
HOMEPAGE = "https://github.com/mnooner256/pyqrcode"
LICENSE = "BSD-3-Clause"
LIC_FILES_CHKSUM = "file://PKG-INFO;md5=02e1d57c98b8dd2bcc1fb78d46d3e153"

SRC_URI[md5sum] = "371f29f4b03bd2830c6e0319258b1259"
SRC_URI[sha256sum] = "fdbf7634733e56b72e27f9bce46e4550b75a3a2c420414035cae9d9d26b234d5"

PYPI_PACKAGE = "PyQRCode"

